on:
  push:
#    branches: [ master ]

name: Notify doc changes
permissions:
  contents: read
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            app: "${{ github.event.repository.name }}"
            status: "${{ job.status }}"
            env: "pre-production"
            msg: "${{ github.event.head_commit.message }}"
            link: "${{ github.event.pull_request.url || github.event.head_commit.url }}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
